name: 2vs2v3
main: TT2\TT2
api: [3.0.0-ALPHA5, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 4.0.0]
version: 0.1 
author: TheAndroidRPZz

commands:
    2vs2:
        usage: /2vs2 <create>
        description: Crear Nueva Arena
    vsstart:
        usage: /vsstart
        description: Comenzar Arena
permissions:
    Owner.op:
        default: op
  